INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (1,null,'HEATING', 20000, null, null, 'Heater', null, null, 'ORDER123', 'HEATER1231', 'Heater in the front');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (2,null,'AIR_CONDITION' ,30000,  null, null, 'Aircon', null, null, 'ORDER456', 'AIRCON1X1', 'Aircon hot days');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (3,null,'MISC' ,40000, null, null, 'AutomaticDrink', null, null, 'ORDER789', 'DRINKHOLDER13321', 'Big Water bottle for xX');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (4,null,'MULTIMEDIA',25000, null, null, 'Radio System XXX', null, null, 'ORDER134', 'RADOIO12131', 'Radio System Stereo ');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (5,null, 'SEATS',60000,  null, null, 'LeatherSeats', null, null, 'ORDER567', 'LEATHER5345', 'Leather seats');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (6,null,'NAVIGATION_SYSTEM' ,65000,  null, null, 'NavigationSystem', null, null, 'ORDERXA1', 'NAVI13231', 'Cheap NavigationSystemxL');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (7,null, 'NAVIGATION_SYSTEM',72000,  null, null, 'NavigationSystemXL', null, null, 'ORDER45464', 'NAVI856', 'Navigation System XXL ');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (8,null, 'MULTIMEDIA',82000, null, null, 'Monitors Back', null, null, 'ORDER8999ZZ', 'MON1313', 'Monitors for Children in the back');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (9,null,'SEATS' ,82000,  null, null, 'Seats Ergo', null, null, 'ORDERXYZXA13133', 'SEATXYZ12', 'Ergonomic Seat for long drives');
INSERT INTO public.special_equipment (id,delete_flag, special_equipment_type, price, created_at, modified_at, equipment_name, created_by, modified_by, order_number, product_id, description) VALUES (10,null,'STEERING_WHEEL' ,10000,  null, null, 'Steering Wheel', null, null, 'ORDERXYZXA13133', 'SEATXYZ', 'SteeringWheel better feeling');

