services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=car_config_db'
      - 'POSTGRES_PASSWORD=secret123'
      - 'POSTGRES_USER=myuserHidden123'
    ports:
      - "5432:5432"
