spring:
  application:
    name: carconfig
  datasource:
    url: "jdbc:postgresql://localhost:5432/car_config_db"
    username: "myuserHidden123"
    password: "secret123"
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    enabled: false
  config:
    import: optional:classpath:./secrets.yaml
server:
  port: 8090
  servlet:
    context-path: "/api"

cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE