spring:
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    username: "sa"
    password: ""
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: "create-drop"
    database-platform: "org.hibernate.dialect.H2Dialect"
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret-key: "MjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMQ=="
    expiration-time: 3600000
  api:
    signup-key: "TEST_SIGNUP_API_KEY"

cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE