package com.computacenter.carconfig.services.order;

import com.computacenter.carconfig.dto.order.CarOrderDto;
import com.computacenter.carconfig.dto.order.CarOrderUpdateDto;
import com.computacenter.carconfig.entities.base.CarColor;
import com.computacenter.carconfig.entities.base.CarEngine;
import com.computacenter.carconfig.entities.base.CarRim;
import com.computacenter.carconfig.entities.base.SpecialEquipment;
import com.computacenter.carconfig.entities.order.*;
import com.computacenter.carconfig.exceptions.OrderException;
import com.computacenter.carconfig.mapper.order.OrderMapper;
import com.computacenter.carconfig.repository.order.*;
import com.computacenter.carconfig.services.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Collections;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

/**
 * Service class for handling business logic related to orders.
 * This class orchestrates data flow between the controller and the repository.
 */
@Service
@RequiredArgsConstructor
public class OrderService {

    private final OrderRepository orderRepository;
    private final OrderUserService orderUserService;

    private final OrderMapper orderMapper;

    private final CarColorOrderService carColorOrderService;
    private final CarEngineOrderService carEngineOrderService;
    private final CarRimOrderService carRimOrderService;
    private final SpecialEquipmentOrderService specialEquipmentOrderService;
    private final OrderStatusService orderStatusService;


    /**
     * Creates a new order by converting a DTO to an entity and saving it.
     *
     * @param orderDto The DTO containing the order data.
     */
    @Transactional
    public String createOrderByIds(CarOrderUpdateDto orderDto) {
        var orderUser = orderUserService.getUserIfExists(orderDto.getUserMail());
        var orderStatus = orderStatusService.createNewOrderStatusWithUser(orderUser);
        var carColorOrder = carColorOrderService.createCarColorsOrderByProductIdAndUser(orderDto.getCarColorProductId(), orderUser);
        var carEngineOrder = carEngineOrderService.createCarEngineOrderByProductIdAndUser(orderDto.getCarEngineProductId(), orderUser);
        var carRimOrder = carRimOrderService.createCarRimOrderProductIdAndOrderUser(orderDto.getCarRimsProductId(), orderUser);
        var specialEquipmentOrder = specialEquipmentOrderService.createSpecialEquipmentsOrdersByProductIdsAndUser(
                orderDto.getSpecialEquipmentProductIds() == null ? Collections.emptyList() : orderDto.getSpecialEquipmentProductIds(),
                orderUser
        );
        var order = new CarOrder();
        order.setCarOrderId(UUID.randomUUID().toString());
        order.setCarColorOrder(carColorOrder);
        order.setCarEngineOrder(carEngineOrder);
        order.setCarRimOrder(carRimOrder);
        order.setSpecialEquipmentOrders(specialEquipmentOrder);
        order.setOrderStatus(orderStatus);
        order.setOrderUser(orderUser);
        var savedOrder =orderRepository.save(order);
        return savedOrder.getCarOrderId();
    }

    /**
     * Retrieves an order by its ID.
     *
     * @param orderId The ID of the order.
     * @return The CarOrderDto if found, otherwise null.
     */
    public Optional<CarOrderDto> getOrderById(String orderId) {
        Optional<CarOrder> orderOptional = orderRepository.findByCarOrderId(orderId);
        return orderOptional.map(orderMapper::toDto);
    }

    /**
     * Updates an existing order.
     *
     * @param orderDto The DTO with the updated data.
     */
    //TODO: generated by junie rework it makes no update.
    @Transactional
    public String updateOrder(CarOrderUpdateDto orderDto) {
        var existingOrderOpt = orderRepository.findByCarOrderId(orderDto.getCarOrderId());
        if (existingOrderOpt.isEmpty()) {
            throw new OrderException("CarOrder not found with id: " + orderDto.getCarOrderId());
        }
        var existingOrder = existingOrderOpt.get();

        // Resolve user (use anonymous if none provided)
        var orderUser = orderUserService.getUserIfExists(orderDto.getUserMail());
        
        existingOrder.setOrderUser(orderUser);
        existingOrder.setUpdatedBy(orderUser.getUserName());

        // Update components only if ids are provided AND differ from current selections
        boolean anythingChanged = false;

        if (Objects.nonNull(orderDto.getCarColorProductId())) {
            var currentColorPid = Optional.ofNullable(existingOrder.getCarColorOrder())
                    .map(CarColorOrder::getCarColor)
                    .map(CarColor::getProductId)
                    .orElse(null);
            if (!orderDto.getCarColorProductId().equals(currentColorPid)) {
                var colorOrder = carColorOrderService.createCarColorsOrderByProductIdAndUser(orderDto.getCarColorProductId(), orderUser);
                existingOrder.setCarColorOrder(colorOrder);
                anythingChanged = true;
            }
        }
        if (Objects.nonNull(orderDto.getCarEngineProductId())) {
            var currentEnginePid = Optional.ofNullable(existingOrder.getCarEngineOrder())
                    .map(CarEngineOrder::getCarEngine)
                    .map(CarEngine::getProductId)
                    .orElse(null);
            if (!orderDto.getCarEngineProductId().equals(currentEnginePid)) {
                var engineOrder = carEngineOrderService.createCarEngineOrderByProductIdAndUser(orderDto.getCarEngineProductId(), orderUser);
                existingOrder.setCarEngineOrder(engineOrder);
                anythingChanged = true;
            }
        }
        if (Objects.nonNull(orderDto.getCarRimsProductId())) {
            var currentRimPid = Optional.ofNullable(existingOrder.getCarRimOrder())
                    .map(CarRimOrder::getCarRim)
                    .map(CarRim::getProductId)
                    .orElse(null);
            if (!orderDto.getCarRimsProductId().equals(currentRimPid)) {
                var rimOrder = carRimOrderService.createCarRimOrderProductIdAndOrderUser(orderDto.getCarRimsProductId(), orderUser);
                existingOrder.setCarRimOrder(rimOrder);
                anythingChanged = true;
            }
        }
        if (Objects.nonNull(orderDto.getSpecialEquipmentProductIds())) {
            var currentSePids = Optional.ofNullable(existingOrder.getSpecialEquipmentOrders())
                    .orElse(Collections.emptyList())
                    .stream()
                    .map(seo -> Optional.ofNullable(seo.getSpecialEquipment()).map(SpecialEquipment::getProductId).orElse(null))
                    .filter(Objects::nonNull)
                    .sorted()
                    .toList();
            var requestedSePids = orderDto.getSpecialEquipmentProductIds().stream().sorted().toList();
            if (!currentSePids.equals(requestedSePids)) {
                var seOrders = specialEquipmentOrderService.createSpecialEquipmentsOrdersByProductIdsAndUser(orderDto.getSpecialEquipmentProductIds(), orderUser);
                existingOrder.setSpecialEquipmentOrders(seOrders);
                anythingChanged = true;
            }
        }
        if (orderDto.getPrice() != null) {
            if (!orderDto.getPrice().equals(existingOrder.getTotalPrice())) {
                existingOrder.setTotalPrice(orderDto.getPrice());
                anythingChanged = true;
            }
        }

        // Mark order as invalidated if anything changed
        if (anythingChanged) {
            existingOrder.setDeleteFlag("Y");
        }

        var savedOrder =orderRepository.save(existingOrder);
        return savedOrder.getCarOrderId();
    }

    /**
     * Deletes an order by its public orderId.
     *
     * @param orderId The public orderId of the order to delete.
     */
    @Transactional
    public void deleteOrder(String orderId) {
        var orderOpt = orderRepository.findByCarOrderId(orderId);
        if (orderOpt.isEmpty()) {
            throw new OrderException("CarOrder not found with id: " + orderId);
        }
        orderRepository.delete(orderOpt.get());
    }


}